# netlify Identity
backend:
  name: git-gateway

locale: nl
# URL is used to display on the top right
display_url: https://nm-style.be

# Folder with images
media_folder: content/assets
# Path that is appended to image location in markdown
public_folder: ../assets

# Disable content preview
editor: 
  preview: false

collections:
  - name: home-page
    label: Home
    files:
      - name: appointment
        label: Afspraak maken
        file: content/home/appointment.md
        fields:
          - { name: layout, label: Layout, widget: hidden, default: home-appointment }
          - { name: thumbnail, label: Foto, widget: image }
          - { name: title, label: Titel, widget: string }
          - { name: description, label: Beschrijving, widget: text }

  - name: blog-page
    label: Nieuws
    files:
      - name: intro
        label: Intro
        file: content/blog/intro.md
        fields:
          - { name: layout, label: Layout, widget: hidden, default: blog-intro }
          - { name: title, label: Titel, widget: string }
          - { name: description, label: Beschrijving, widget: text, required: false }
          - { name: thumbnail, label: Foto, widget: image, required: false }
      - name: articles-list
        label: Artikels
        file: content/blog/articles.md
        fields:
          - { name: layout, label: Layout, widget: hidden, default: blog-articles }
          - name: articles
            label: Artikels
            widget: list
            collapsed: true
            summary: '{{fields.title}}'
            label_singular: artikel
            fields:
              - { name: thumbnail, label: Foto, widget: image }
              - { name: date, label: Datum, widget: date, date_format: true }
              - { name: title, label: Titel, widget: string }
              - { name: description, label: Korte beschrijving, widget: text }
              - { name: facebookUrl, label: Link naar facebook, widget: string }

  - name: prices-page
    label: Prijslijst
    files:
      - name: intro
        label: Intro
        file: content/prices/intro.md
        fields:
          - { name: layout, label: Layout, widget: hidden, default: prices-intro }
          - { name: title, label: Titel, widget: string }
          - { name: description, label: Beschrijving, widget: text, required: false }
          - { name: thumbnail, label: Foto, widget: image, required: false }
      - name: categories-list
        label: Prijslijst
        file: content/prices/services.md
        fields:
          - { name: layout, label: Layout, widget: hidden, default: prices-categories }
          - name: categories
            label: Categorieën
            widget: list
            collapsed: true
            summary: '{{fields.title}}'
            label_singular: categorie
            fields:
              - { name: title, label: Titel, widget: string }
              - { name: thumbnail, label: Foto, widget: image }
              - name: services
                label: Diensten
                widget: list
                collapsed: true
                summary: '{{fields.name}} - {{fields.price}}'
                label_singular: dienst
                fields:
                  - { name: name, label: Titel, widget: string }
                  - { name: price, label: Prijs, widget: string, required: false }
      - name: cta
        label: Online afspraak banner
        file: content/prices/cta.md
        fields:
          - { name: layout, label: Layout, widget: hidden, default: prices-cta }
          - { name: title, label: Titel, widget: string }
          - { name: description, label: Beschrijving, widget: text }

  - name: products-page
    label: Producten
    files:
      - name: banner
        label: Banner
        file: content/products/banner.md
        fields:
          - { name: layout, label: Layout, widget: hidden, default: products-banner }
          - { name: title, label: Titel, widget: string }
          - { name: description, label: Beschrijving, widget: text }
          - { name: thumbnail, label: Foto, widget: image, required: false }
      - name: block1
        label: Blok zonder foto
        file: content/products/block1.md
        fields:
          - { name: layout, label: Layout, widget: hidden, default: products-block1 }
          - { name: title, label: Titel, widget: string }
          - { name: description, label: Alineas, widget: text }
      - name: block2
        label: Blok met foto rechts
        file: content/products/block2.md
        fields:
          - { name: layout, label: Layout, widget: hidden, default: products-block2 }
          - { name: title, label: Titel, widget: string }
          - { name: description, label: Beschrijving, widget: text }
          - { name: thumbnail, label: Foto, widget: image }
      - name: block3
        label: Blok met foto links
        file: content/products/block3.md
        fields:
          - { name: layout, label: Layout, widget: hidden, default: products-block3 }
          - { name: title, label: Titel, widget: string }
          - { name: description, label: Beschrijving, widget: text }
          - { name: thumbnail, label: Foto, widget: image }

  - name: reviews-page
    label: Reviews
    files:
      - name: intro
        label: Intro
        file: content/reviews/intro.md
        fields:
          - { name: layout, label: Layout, widget: hidden, default: reviews-intro }
          - { name: title, label: Titel, widget: string }
          - { name: description, label: Beschrijving, widget: text, required: false }
          - { name: thumbnail, label: Foto, widget: image, required: false }
      - name: reviews-list
        label: Reviews
        file: content/reviews/reviews.md
        fields:
          - { name: layout, label: Layout, widget: hidden, default: reviews-reviews }
          - name: reviews
            label: Reviews
            widget: list
            collapsed: true
            summary: '{{fields.title}}'
            label_singular: review
            fields:
              - name: images
                label: Foto's
                widget: list
                collapsed: true
                label_singular: foto
                field: { name: thumbnail, label: Foto, widget: image, max: 3 }
              - { name: title, label: Titel, widget: string }
              - { name: description, label: Beschrijving, widget: text }
      - name: cta
        label: Online afspraak banner
        file: content/reviews/cta.md
        fields:
          - { name: layout, label: Layout, widget: hidden, default: reviews-cta }
          - { name: title, label: Titel, widget: string }
          - { name: description, label: Beschrijving, widget: text }

  - name: about-page
    label: Over
    files:
      - name: about
        label: Over jezelf
        file: content/about/about.md
        fields:
          - { name: layout, label: Layout, widget: hidden, default: about-about }
          - { name: title, label: Titel, widget: string }
          - { name: thumbnail, label: Foto, widget: image }
          - { name: description, label: Beschrijving, widget: text }
      - name: timeline-list
        label: Tijdslijn
        file: content/about/timeline.md
        fields:
          - { name: layout, label: Layout, widget: hidden, default: about-timeline }
          - name: timeline
            label: Tijdslijn
            widget: list
            collapsed: true
            summary: '{{fields.time}} - {{fields.title}}'
            label_singular: tijdstip
            fields:
              - { name: time, label: Tijdstip, widget: string }
              - { name: title, label: Titel, widget: string }
              - { name: description, label: Beschrijving, widget: text }