backend:
  name: git-gateway

locale: nl

media_folder: content/assets
public_folder: ../assets

collections:
  - name: appointment
    label: Home - Maak afspraak
    folder: content/home
    fields:
      - { name: thumbnail, label: Foto, widget: image}
      - { name: title, label: Titel, widget: string }
      - { name: description, label: Beschrijving, widget: text }
  - name: blog
    label: Nieuws
    folder: content/blog
    create: true
    fields:
      - { name: thumbnail, label: Foto, widget: image}
      - { name: date, label: Datum, widget: date, format: DD-MM-YYYY }
      - { name: title, label: Titel, widget: string }
      - { name: description, label: Korte beschrijving, widget: text }
      - { name: facebookUrl, label: Link naar facebook, widget: string }