backend:
  name: git-gateway

locale: nl
display_url: https://nm-style.be

media_folder: content/assets
public_folder: ../assets

collections:
  - name: home-page
    label: Home pagina
    files:
      - name: appointment
        label: Afspraak maken
        file: content/home/appointment.md
        fields:
          - { name: layout, widget: hidden, default: home-appointment}
          - { name: thumbnail, label: Foto, widget: image }
          - { name: title, label: Titel, widget: string }
          - { name: description, label: Beschrijving, widget: text }

  - name: blog-page
    label: Nieuws pagina
    files:
      - name: intro
        label: Intro
        file: content/blog/intro.md
        fields:
          - { name: layout, widget: hidden, default: blog-intro}
          - { name: title, label: Titel, widget: string }
          - { name: description, label: Beschrijving, widget: text, required: false }
          - { name: thumbnail, label: Foto, widget: image, required: false }
  - name: articles
    label: Artikels
    folder: content/articles
    create: true
    fields:
      - { name: layout, widget: hidden, default: article }
      - { name: thumbnail, label: Foto, widget: image }
      - { name: date, label: Datum, widget: date, date_format: true }
      - { name: title, label: Titel, widget: string }
      - { name: description, label: Korte beschrijving, widget: text }
      - { name: facebookUrl, label: Link naar facebook, widget: string }

  - name: prices-page
    label: Prijslijst pagina
    files:
      - name: intro
        label: Intro
        file: content/prices/intro.md
        fields:
          - { name: layout, widget: hidden, default: prices-intro }
          - { name: title, label: Titel, widget: string }
          - { name: description, label: Beschrijving, widget: text, required: false }
          - { name: thumbnail, label: Foto, widget: image, required: false }
      - name: service-categories
        label: Prijslijst
        file: content/prices/services.md
        fields:
          - { name: layout, widget: hidden, default: prices-categories}
          - name: categories
            label: Categorieën
            widget: list
            summary: '{{fields.title}}'
            label_singular: categorie
            fields:
              - { name: title, label: Titel, widget: string }
              - { name: thumbnail, label: Foto, widget: image }
              - name: services
                label: Diensten
                widget: list
                collapsed: true
                summary: '{{fields.name}} - {{fields.price}}'
                label_singular: dienst
                fields:
                  - { name: name, label: Titel, widget: string }
                  - { name: price, label: Prijs, widget: string, required: false }